In [1]:
# Necessary Libraries
import pandas as pd
import ast
import sys
import os
target = os.path.abspath(os.path.abspath(''))
while(target.split("\\")[-1]!="Road"):
    target = os.path.dirname(target)
sys.path.append(target)

In [2]:
from source.features import feature_selected as FS

In [3]:
data = pd.read_csv('../data/raw/data.csv')

In [4]:
data.head(10)

,_,id,peer_id,date,message,out,mentioned,media_unread,silent,post,...,entities,views,forwards,replies,edit_date,post_author,grouped_id,reactions,restriction_reason,ttl_period
0,Message,409414,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:48:25+00:00,.,True,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
1,Message,409427,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:02+00:00,حواره للخارج من نابلس ؟,False,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
2,Message,409428,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:09+00:00,سالك سالك,False,False,False,False,False,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],86400
3,Message,409429,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:18+00:00,حوارة في عليها مستوطنين,False,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
4,Message,409430,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:26+00:00,وين,False,False,False,False,False,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],86400
5,Message,409431,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:35+00:00,كيف طريق من طوباس لرام الله,False,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
6,Message,409432,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:37+00:00,سلام,False,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
7,Message,409433,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:37+00:00,لا مافب,False,False,False,False,False,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],86400
8,Message,409434,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:39+00:00,شو وضع المربعه ؟,False,False,False,False,False,...,[],NaN,NaN,"{'_': 'MessageReplies', 'replies': 0, 'replies...",NaN,NaN,NaN,NaN,[],86400
9,Message,409435,"{'_': 'PeerChannel', 'channel_id': 1756020315}",2023-03-07 13:50:47+00:00,في حاجز بس سالك,False,False,False,False,False,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],86400

In [5]:
# Remove unnecessary columns based on usefulness of it
FS.delete_unnecessery_columns(data=data)
# Display the columns after cleaned
data.columns

Index(['id', 'date', 'message', 'from_id', 'reply_to'], dtype='object')

In [6]:
# Extract the date and time to separate columns
data['year'], data['month'], data['day'], data['hour'], data['minute'], data['second'] = FS.extract_dates(date=data['date'])
# Remove the date column cause it has become useless
data.drop(columns='date', inplace=True)
# Display the columns after cleaned
data

,id,message,from_id,reply_to,year,month,day,hour,minute,second
0,409414,.,"{'_': 'PeerUser', 'user_id': 5774169366}",NaN,2023,3,7,13,48,25
1,409427,حواره للخارج من نابلس ؟,"{'_': 'PeerUser', 'user_id': 325418964}",NaN,2023,3,7,13,50,2
2,409428,سالك سالك,"{'_': 'PeerUser', 'user_id': 1827882971}","{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,7,13,50,9
3,409429,حوارة في عليها مستوطنين,"{'_': 'PeerUser', 'user_id': 5633332941}",NaN,2023,3,7,13,50,18
4,409430,وين,"{'_': 'PeerUser', 'user_id': 1332172310}","{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,7,13,50,26
...,...,...,...,...,...,...,...,...,...,...
17301,428597,كيف طريق صرة,"{'_': 'PeerUser', 'user_id': 939291539}",NaN,2023,3,16,20,53,57
17302,428598,و دوار كدوميم,"{'_': 'PeerUser', 'user_id': 939291539}",NaN,2023,3,16,20,54,7
17303,428599,شو وضع dso,"{'_': 'PeerUser', 'user_id': 5767031256}",NaN,2023,3,16,20,55,10
17304,428600,جيت صرة سالكة,"{'_': 'PeerUser', 'user_id': 5693518787}","{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,16,20,57,24
17305,428601,واد قانا سالك ؟,"{'_': 'PeerUser', 'user_id': 2111855532}",NaN,2023,3,16,21,1,20

In [7]:
# Extract the ID of the user who sent the message
data['from_id'] = data['from_id'].apply(lambda x: FS.extract_id(json_string=x, target_id='user_id'))
# Display the columns after cleaned
data

,id,message,from_id,reply_to,year,month,day,hour,minute,second
0,409414,.,5774169366,NaN,2023,3,7,13,48,25
1,409427,حواره للخارج من نابلس ؟,325418964,NaN,2023,3,7,13,50,2
2,409428,سالك سالك,1827882971,"{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,7,13,50,9
3,409429,حوارة في عليها مستوطنين,5633332941,NaN,2023,3,7,13,50,18
4,409430,وين,1332172310,"{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,7,13,50,26
...,...,...,...,...,...,...,...,...,...,...
17301,428597,كيف طريق صرة,939291539,NaN,2023,3,16,20,53,57
17302,428598,و دوار كدوميم,939291539,NaN,2023,3,16,20,54,7
17303,428599,شو وضع dso,5767031256,NaN,2023,3,16,20,55,10
17304,428600,جيت صرة سالكة,5693518787,"{'_': 'MessageReplyHeader', 'reply_to_msg_id':...",2023,3,16,20,57,24
17305,428601,واد قانا سالك ؟,2111855532,NaN,2023,3,16,21,1,20

In [8]:
# Extract the ID of the message being replied to, if any.
data['reply_to'] = data['reply_to'].apply(lambda x: FS.extract_id(json_string=x, target_id='reply_to_msg_id'))
# Display the columns after cleaned
data

,id,message,from_id,reply_to,year,month,day,hour,minute,second
0,409414,.,5774169366,-1,2023,3,7,13,48,25
1,409427,حواره للخارج من نابلس ؟,325418964,-1,2023,3,7,13,50,2
2,409428,سالك سالك,1827882971,409427,2023,3,7,13,50,9
3,409429,حوارة في عليها مستوطنين,5633332941,-1,2023,3,7,13,50,18
4,409430,وين,1332172310,409429,2023,3,7,13,50,26
...,...,...,...,...,...,...,...,...,...,...
17301,428597,كيف طريق صرة,939291539,-1,2023,3,16,20,53,57
17302,428598,و دوار كدوميم,939291539,-1,2023,3,16,20,54,7
17303,428599,شو وضع dso,5767031256,-1,2023,3,16,20,55,10
17304,428600,جيت صرة سالكة,5693518787,428597,2023,3,16,20,57,24
17305,428601,واد قانا سالك ؟,2111855532,-1,2023,3,16,21,1,20

In [9]:
data.to_csv('../data/interim/feature_selected.csv', index=False)